trigger: none

pr: none

resources:
  pipelines:
    - pipeline: trigger1
      source: leriksen.trigger1
      project: triggering
      trigger:
        branches:
          include:
            - '*'

steps:
  - checkout: none
  - script: echo trigger2
